CREATE OR REPLACE TABLE RAW.ORDERS_RAW (
  order_id INT,
  customer_id INT,
  order_date DATE,
  amount FLOAT,
  status STRING,
  ingestion_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CURATED.FACT_ORDERS AS
SELECT * FROM RAW.ORDERS_RAW WHERE 1=0;

CREATE TABLE IF NOT EXISTS DQ.CHECK_RESULTS (
  check_name STRING,
  fail_count INT,
  run_time TIMESTAMP
);